<div class="container">
    <div class="newsletter-template">
        <div class="news-icon">
            <img src="./img/tna-newsletter-icon.png"
                 alt="The National Archives Newsletter Icon"/>
        </div>

        <div class="news-content" id="newsletterAccessibility">
            <h2>Send me The National Archives’ newsletter</h2>
            <p>A monthly round-up of news, blogs, offers and events</p>
        </div>

        <div class="news-form">
            <form name="signup" id="signup" action="https://r1-t.trackedlink.net/signup.ashx" method="post" role="form">
                <input type="hidden" name="addressbookid" value="636353"> <!-- homepage and general sign up -->
                <!-- input type="hidden" name="addressbookid" value="732466" --> <!-- first world war portal sign up -->
                <input type="hidden" name="userid" value="173459">
                <input type="hidden" name="cd_SOURCE" value="web">
                <input type="hidden" name="ReturnURL"
                       value="http://www.nationalarchives.gov.uk/about/get-involved/newsletters/the-national-archives-newsletter/thank-you/">
                <label for="Email">Send me The National Archives’ newsletter</label>
                <input type="email" name="Email" id="Email" required="required"
                       placeholder="Enter your email address" aria-labelledby="newsletterAccessibility">
                <input id="newsletterSignUp" type="submit" name="Submit" value="Subscribe" class="margin-left-medium">
            </form>
        </div>
    </div>
</div>