<link rel='stylesheet' id='tna-google-fonts-css'
      href='https://fonts.googleapis.com/css?family=Open+Sans%3A400%2C700%2C400italic%2C700italic%7CBitter&#038;ver=4.4.11'
      type='text/css' media='all'/>
<link rel='stylesheet' href="css/base-sass.min.css"/>

<!-- Fav icon -->
<link rel="shortcut icon" type="image/vnd.microsoft.icon" href="img/favicon.ico">
<link rel="icon" type="image/vnd.microsoft.icon" href="img/favicon.ico">